#!/bin/bash

while true; do
	ruby nmrstat_html.rb
	ruby main.rb
#	cp ui.css /Volumes/dzengy/homepage/
	cp ui.css /var/www/html/
#	cp /private/var/log/apache2/access_log /Volumes/dzengy/homepage/mbplog
#	cp oanmr*_hist /home/pi/slab1/homepage/
	echo 'sleep for 30s'
	sleep 30s
done
